apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: postgres
  namespace: phrase
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: timezone-converter
    app.kubernetes.io/version: "15.1"

spec:
  replicas: 1
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/part-of: timezone-converter

  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/part-of: timezone-converter
        app.kubernetes.io/version: "15.1"

    spec:

      volumes:
        - name: init-scripts
          configMap:
            name: postgres-init-scripts

      containers:
        - name: postgres
          image: postgres:15.1

          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d

          envFrom:
            - secretRef:
                name: postgres-env

          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          ports:
            - name: postgresql
              protocol: TCP
              containerPort: 5432

  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: phrase

      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi
