apiVersion: v1
kind: ConfigMap

metadata:
  name: postgres-init-scripts
  namespace: phrase

data:
  setup.sh: |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      CREATE USER timezone_converter WITH PASSWORD '$TIMEZONE_CONVERTER_PASSWORD';
      CREATE DATABASE timezone_converter;
      GRANT ALL PRIVILEGES ON DATABASE timezone_converter TO timezone_converter;
    EOSQL
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname timezone_converter <<-EOSQL
      CREATE SCHEMA AUTHORIZATION timezone_converter;
    EOSQL

