apiVersion: apps/v1
kind: Deployment

metadata:
  name: timezone-converter
  namespace: phrase
  labels:
    app.kubernetes.io/name: timezone-converter
    app.kubernetes.io/part-of: timezone-converter
    app.kubernetes.io/version: 0.1.0

spec:
  replicas: 1
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app.kubernetes.io/name: timezone-converter
      app.kubernetes.io/part-of: timezone-converter

  template:
    metadata:
      labels:
        app.kubernetes.io/name: timezone-converter
        app.kubernetes.io/part-of: timezone-converter
        app.kubernetes.io/version: 0.1.0

    spec:
      initContainers:
        - name: timezone-converter-migrations
          image: cschmatzler/timezone-converter:latest
          imagePullPolicy: Always

          command:
            - "/app/bin/migrate"

          envFrom:
            - secretRef:
                name: timezone-converter-env

      containers:
        - name: timezone-converter
          image: cschmatzler/timezone-converter:latest
          imagePullPolicy: Always

          envFrom:
            - secretRef:
                name: timezone-converter-env

          ports:
            - name: http
              protocol: TCP
              containerPort: 4000
